# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Knowledge Management Playbook
email: mark.vogelgesang@gsa.gov
description: "A playbook to ensuring successful collection and dissemination of knowledge throughout the federal government."
baseurl: "/teamKnow" # the subpath of your site, e.g. /blog
url: "https://mvogelgesang.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  mvogelgesang
google_analytics_ua: UA-118037805-1

#Github information
repository: mvogelgesang/teamKnow
# Build settings
markdown: kramdown
remote_theme: 18F/uswds-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    url:
      boost: 5
    body:
